import type { Metadata } from "next";
import "./globals.css";
import { Sidebar, SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "@/components/layout";

export const metadata: Metadata = {
  title: "zinyAdmin",
  description: "Generated by zinyAdmin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main>
          <SidebarProvider>
            <Sidebar />
            <SidebarInset>
              <Header />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </main>
      </body>
    </html>
  );
}
